<?php

/**
 * RutaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RutaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RutaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ruta');
    }
}