<?php

/**
 * RutaUbicacionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RutaUbicacionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RutaUbicacionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RutaUbicaciones');
    }
}